CREATE DATABASE burgersDB;

USE burgersDB;

CREATE TABLE burgers(
id INT NOT NULL AUTO_INCREMENT,
burger_name VARCHAR(250) NOT NULL,
devoured BOOLEAN NOT NULL DEFAULT 0,
PRIMARY KEY(id)
);

DESCRIBE burgers;